### PR TITLE
I've changed Bökeys

### PR DESCRIPTION
**Pull request by SchlauraStern**

### CODE REVIEW

**Comment by enginbo** [comment]
Why Laura. Why

**Comment by enginbo** [comment]
You ruined everything

**Review by tgfassina — CHANGES_REQUESTED** [review]
Please fix conflicts

**Comment by SchlauraStern** [comment]
What ?? What you doing here? @tgfassina

**Comment by anseitz** [comment]
https://geoguessr.com/challenge/ScdsEMOb8kbaTLUg

**Comment by enginbo** [comment]
Jojo and my stuff is in there Laura, get out of master. We don't want to do all our shit over again

**Pull request merged**
